#!/bin/bash

# Ensure XDG locations are defined
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state

export HISTFILE="$XDG_STATE_HOME"/bash/history

export VIMINIT="set nocp | source ${XDG_CONFIG_HOME}/vim/vimrc"


# Load default system settings
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Load custom bash settings
if [ -f "$XDG_CONFIG_HOME/bash/bashrc" ]; then
    . "$XDG_CONFIG_HOME/bash/bashrc"
fi
